// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twgsrxqxehykvcvwoeqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Z3NyeHF4ZWh5a3ZjdndvZXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzgwMzksImV4cCI6MjA2NzA1NDAzOX0.JjxjrphTPj3_23sAv6QEYLyGQkQP6jWTeinFRmvtJxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});